### ISSUE TITLE
LTC6820 CRC Error Handling

### ISSUE THREAD

**Issue by Sabramz** [Northeastern-Electric-Racing/ShepherdBMS-2#124]
### Description

We currently calculate CRCs for the isoSPI on the LTC6820, but we do not handle the errors, or so I have been told. We need CRCs because a) Every communication susceptible to digital noise NEEDS a CRC b) We need to find out if we are failing CRCs on the isoSPI line. This may require editing embedded base. Handling what happens with the results of CRCs will be a future ticket.

### Acceptance Criteria

- [ ] CRCs are calculated
- [ ] The results of CRC calculations are passed through the application

### Proposed Solution

Find where CRCs are calculated and pass the result through Shep to some interface that is monitored.

**Comment by dyldonahue** [comment]
@Sabramz closing since done yes?
