### ISSUE TITLE
Port LTC6804 driver to STM32

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/ShepherdBMS-2#13]
the LTC6804 chip directly monitors our battery, and transmits the data to Shepherd Controller via SPI. 

Right now Shepherd 1.0 has the LTC6804 driver that is dependent on the NERduino SPI implementation. We need to redo some of the LTC initialization functions to take in an LTC struct similar to how we've been doing some Cerberus drivers AND probably set up the SPI line

**Comment by dyldonahue** [comment]
closing because i moved to `Embedded-Base` [here](https://github.com/Northeastern-Electric-Racing/Embedded-Base/issues/7)
