### ISSUE TITLE
[Bug] - DCL message not being sent.

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/ShepherdBMS-2#134]
### Observed Behavior

The DCL message (0x156) is not being sent with the contents of the DCL.

### Expected Behavior

The DCL message should have been sent.  Introduced in rtos rewrite.

### Steps to Reproduce

See no message sending

**Comment by harrison-e** [comment]
Is the message being sent at all? If so, what does it look like?

**Comment by jr1221** [comment]
No.  But it exists in code.  It's message 0x156 if u search for that you should fine the line where it is sent.

**Comment by harrison-e** [comment]
Fake issue
