### ISSUE TITLE
[Compute] - Add in PWM to control fan

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/ShepherdBMS-2#72]
### Current Features

Currently we are controlling fan speed with PWM but in the old AMS configuration. We need update this to the new fan configuration and set up STM to do this.

### Desired Additional Features

- STM configuration (figure out PWM in CubeMX)
- Update control code

TASKS

- [] Figure out how to utilize timers and change PWM. The 5 Fan pins are set to output based on specific timer channels, but I dont know how to actually change PWM duty cycle on these timers (and, can different channels of the same timer have differnt duty cycles?) FIgure this out, and directly replace the old Nerdiuno set duty cycle function with thse logic

- [ ] Add the logic to toggle individual fans

- [ ] Create a wrapper function to actually apply the logic for toggling individual fans. This will likely follow this high level logic : "When this particular area gets to this temperature, toggle its fan to this speed". I will update this ticket when specifics on that are known

**Comment by dyldonahue** [comment]
Note: 

Fan 1 (pin PA10) --> Timer 1, Channel 3
Fan 2 (pin PA8)--> Timer 1,  Channel 1
Fan 3 (pin PC9) --> Timer 8, Channel 4
Fan 4 (pin PC8) --> Timer 8, Channel 3
Fan 5 (pin PC7) --> TImer 8, Channel 2
Fan 6 (pin PC6) --> Timer 8, Channel 1
